version: "3.8"

services:
  app:
    build:
      context: .
    container_name: app
    restart: unless-stopped
    environment:
      - REGION_PROXY=34.76.212.96
      - PORT=8000
      - THREADS=8
    ports:
      - '80:8000' 
    volumes:
      - ./templates:/app/templates
      - ./main.py:/app/main.py
