version: "3.8"

  # ----------------------- Ports Used -------------------------- #
  # Nginx:
  #   - HTTP Traffic = 80
  #   - HTTPS Traffic = 443
  # ------------------------------------------------------------- #

services:
  # -----------------------  Proxy ------------------------------ #
  proxy:
    build:
      context: proxy
    container_name: proxy
    restart: unless-stopped
    ports:
      - '80:8000' 
    volumes:
      - ./proxy/data:/usr/src/app/data
      - ./proxy/src:/usr/src/app/src
    networks:
      - regional
  # ------------------------------------------------------------- #
networks:
  regional:
    name: network_regional