version: "3.8"

  # ----------------------- Ports Used -------------------------- #
  # Nginx:
  #   - HTTP Traffic = 80
  #   - HTTPS Traffic = 443
  # ------------------------------------------------------------- #

services:
  # -----------------------  Proxy ------------------------------ #
  proxy:
    build:
      context: proxy
    container_name: proxy
    restart: unless-stopped
    environment:
      - CHUNK_SIZE=4096
      - THREADS=8
      - PORT=8000
    ports:
      - '80:8000' 
    volumes:
      - ./proxy/main.py:/app/main.py
      - ./proxy/app.py:/app/app.py

    networks:
      - regional
  # ------------------------------------------------------------- #
networks:
  regional:
    name: network_regional